swagger-ui.enabled=true
swagger-ui.version=5.17.14
micronaut.openapi.openapi30.enabled=true
micronaut.openapi.openapi30.json-schema-dialect=https://spec.openapis.org/oas/3.0/dialect/base
micronaut.openapi.filename=device-template-demo
swagger-ui.deepLinking=true
swagger-ui.docExpansion=none
swagger-ui.filter=true
