package ru.aritmos.dtt.demo.openapi;

/**
 * Подготовленные примеры для Swagger UI.
 */
public final class DttSwaggerExamples {

    private DttSwaggerExamples() {
    }

    public static final String SAMPLE_DTT_DISPLAY_BASE64 = "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA==";
    public static final String SAMPLE_DTT_TERMINAL_BASE64 = "UEsDBBQAAAAIAAAAIQBcBbHLWwEAAHICAAAMAAAAbWFuaWZlc3QueW1sbVLJTsMwEL37K6Kc4FCUnhC50aYVEaiqlNADF2SciWrhTV4KucFvcOQLuCAhtm9w/wg3XdQFyZI9897MvJlxLTXHdoQ5pFFWlqhu7QloQ6VIo+5JgogGbKE6t2kUd89Ok07SDadMkrQ9N/Ga0WvSqIIZJdCxwBULvg6jdxrrBq3uTWIn7oV8EGjJLxsFeZVGFjSnArMt91JaeQhk1IQSzRL3r/59/uS//Yf/8W/+KzryL+H9O3/2n8fbQWCIpsq2GvaDtniXVAQ5IKxubpWkwiLjlJLamv6UsipriSaNaswMICKFxVSYK1oDaQiDoi1ygA9mIeMFFhULY9gH+5LzAB34s42ooRNkoXxDUViH7sPQCjIFjne2VkGNHbMTzByYXBDmKlhMWDtA8IjDeuBfbN3nWMuaMsj5wtrDehoLMt2FpNNkNbbrUTEe9PNhPshW/sKF3nT4HnGM/gBQSwMEFAAAAAgAAAAhAL1McL1PAAAAZQAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSKEktys3MS8zhykvMTbVSCIFxUzKLC3ISK/3AohcWXdh6seHCngs7Luy9sOHCbgWNC7OA7H0XGy/s0uRKSS1OLsosKMnMz8NUygUAUEsDBBQAAAAIAAAAIQCEhcHsQAAAAEkAAAAjAAAAdGVtcGxhdGUvZGV2aWNlLXR5cGUtcGFyYW1ldGVycy55bWwrKEpNy6yw4lJQKEvMKU21UvB2DOEqKMrMK0ktCk4tKstMTg0N8kGSV8ooKSmw0tc3NDLXMwBCQysLAwsTJS4AUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQDXG12/HgAAABwAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSM0rKaqML8jPzCvhAgBQSwMEFAAAAAgAAAAhAISFwexAAAAASQAAABsAAAB0ZW1wbGF0ZS9kZWZhdWx0LXZhbHVlcy55bWwrKEpNy6yw4lJQKEvMKU21UvB2DOEqKMrMK0ktCk4tKstMTg0N8kGSV8ooKSmw0tc3NDLXMwBCQysLAwsTJS4AUEsDBBQAAAAIAAAAIQA3sgM8PQAAAEsAAAAbAAAAdGVtcGxhdGUvZXhhbXBsZS12YWx1ZXMueW1sKyhKTcussOJSUChLzClNtVLwDwviKijKzCtJLQpOLSrLTE4NDfJBklfKKCkpsNLXNzTQgyErCwMLEyUuAFBLAwQUAAAACAAAACEAN7IDPD0AAABLAAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sKyhKTcussOJSUChLzClNtVLwDwviKijKzCtJLQpOLSrLTE4NDfJBklfKKCkpsNLXNzTQgyErCwMLEyUuAFBLAwQUAAAACAAAACEANK/LN2YAAACiAAAAIgAAAGV4YW1wbGVzL2JyYW5jaC12YWx1ZXMtZXhhbXBsZS55bWxLKkrMS85ILbbiUlBIArN1DUFsBYWU1LLM5NSQygKIJAiUpBblZuYl5sD4CgoFRalpmRUIvoJCWWJOaaqVgn9YEJKizDyg1uDUIpCJoUE+WNQrZZSUFFjp6xsa6MGQlYWBhYkSFwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEAXAWxy1sBAAByAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAL1McL1PAAAAZQAAABgAAAAAAAAAAAAAAIABhQEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQCEhcHsQAAAAEkAAAAjAAAAAAAAAAAAAACAAQoCAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAYsCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIAB0wIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEA1xtdvx4AAAAcAAAAGgAAAAAAAAAAAAAAgAEnAwAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEAhIXB7EAAAABJAAAAGwAAAAAAAAAAAAAAgAF9AwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhADeyAzw9AAAASwAAABsAAAAAAAAAAAAAAIAB9gMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQA3sgM8PQAAAEsAAAAjAAAAAAAAAAAAAACAAWwEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQA0r8s3ZgAAAKIAAAAiAAAAAAAAAAAAAACAAeoEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABkAUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAANIFAAAAAA==";
    public static final String SAMPLE_DTT_RECEPTION_BASE64 = "UEsDBBQAAAAIAAAAIQBEp+2wQwEAAGUCAAAMAAAAbWFuaWZlc3QueW1sfVJLTsMwFNznFFH2RekK4R1tWhGBqoqELtgZ+0W18Cd6tgvZcQPECbgCSxZwh/RGuOlH/QnJkvVmxn4zfq4MKuomVAGJs7KMqq6eAVphNIn7F2nEEKgDfu1InPSvLtNe2g+rTFPSrcdkqxg0JOawEAx6DlQtA9aT4gkpNtFm313s9bM2Lzpa68umhpyTGIFB7YJgD197uz/DZMKGJs1a0H4u39rv5Uf70/62X8v3fR1YhqI7/a/uVugDD9bXtUFnh3MhedbJLIkrKi1EzGhHhbZ3ogLWMAlF1+KEHy1AuxuquQzJj8mhUSpQJ3i2szT2mq287CQ1xRDXARZsDooeDIpDRb10Myo92Fwz6TmEQA49RPBKw0TgLLfNOUVTCQm5WlVH3ACpZvNDynhkm0d7mBTT0TAf56Nsgxc+ZMPwI5Ik+gNQSwMEFAAAAAgAAAAhADlRPG0/AAAAWgAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSKEpNTi0oyczP48pLzE21UgiC81MyiwtyEiv9wMIX5l9suLDj4sQLey7svbDhYj9XSmpxclEmWCUWWQBQSwMEFAAAAAgAAAAhADVGOzIqAAAANgAAACMAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSKCkqTeUqzsgvDyxNLU0tRpcBAFBLAwQUAAAACAAAACEABrCh3QUAAAADAAAAJQAAAHRlbXBsYXRlL2RldmljZS1wYXJhbWV0ZXJzLXNjaGVtYS55bWyrruUCAFBLAwQUAAAACAAAACEAdljr1RoAAAAYAAAAHAAAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWwrzi8tSk71zsxLsVII9QsOcHX2dPN0deECAFBLAwQUAAAACAAAACEAdFSePRwAAAAaAAAAGgAAAHRlbXBsYXRlL2JpbmRpbmctaGludHMueW1sS0kty0xODaksSPXOzEuxUihKTU4tKMnMz+MCAFBLAwQUAAAACAAAACEANUY7MioAAAA2AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSKCkqTeUqzsgvDyxNLU0tRpcBAFBLAwQUAAAACAAAACEALzBs1zAAAAA3AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSSEvMKU7lKs7ILw8sTS1NLUaSKikqTeUCAFBLAwQUAAAACAAAACEALzBs1zAAAAA3AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1syy3NKckMTi0qy0xOteJSUChLzClNtVJIS8wpTuUqzsgvDyxNLU0tRpIqKSpN5QIAUEsDBBQAAAAIAAAAIQDn7CppXAAAAI8AAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkCBSlJqcWlGTm58EEFBRyS3NKMoNTi0BqEaIKCmWJOaWpVgppiTnFqXDh4oz88sDS1FKEiUhKS4pKU7kAUEsDBBQAAAAIAAAAIQAXcSNNEAAAAA4AAAAUAAAAUkVBRE1FLUlOLUFSQ0hJVkUubWRTVnAJCVFwLErOyCxL5QIAUEsBAhQDFAAAAAgAAAAhAESn7bBDAQAAZQIAAAwAAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0LnltbFBLAQIUAxQAAAAIAAAAIQA5UTxtPwAAAFoAAAAYAAAAAAAAAAAAAACAAW0BAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWxQSwECFAMUAAAACAAAACEANUY7MioAAAA2AAAAIwAAAAAAAAAAAAAAgAHiAQAAdGVtcGxhdGUvZGV2aWNlLXR5cGUtcGFyYW1ldGVycy55bWxQSwECFAMUAAAACAAAACEABrCh3QUAAAADAAAAJQAAAAAAAAAAAAAAgAFNAgAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbFBLAQIUAxQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAAAAAAAAAAACAAZUCAAB0ZW1wbGF0ZS90ZW1wbGF0ZS1vcmlnaW4ueW1sUEsBAhQDFAAAAAgAAAAhAHRUnj0cAAAAGgAAABoAAAAAAAAAAAAAAIAB6QIAAHRlbXBsYXRlL2JpbmRpbmctaGludHMueW1sUEsBAhQDFAAAAAgAAAAhADVGOzIqAAAANgAAABsAAAAAAAAAAAAAAIABPQMAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAvMGzXMAAAADcAAAAbAAAAAAAAAAAAAACAAaADAAB0ZW1wbGF0ZS9leGFtcGxlLXZhbHVlcy55bWxQSwECFAMUAAAACAAAACEALzBs1zAAAAA3AAAAIwAAAAAAAAAAAAAAgAEJBAAAZXhhbXBsZXMvcHJvZmlsZS12YWx1ZXMtZXhhbXBsZS55bWxQSwECFAMUAAAACAAAACEA5+wqaVwAAACPAAAAIgAAAAAAAAAAAAAAgAF6BAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQAXcSNNEAAAAA4AAAAUAAAAAAAAAAAAAACAARYFAABSRUFETUUtSU4tQVJDSElWRS5tZFBLBQYAAAAACwALACsDAABYBQAAAAA=";

    public static final String IMPORT_PROFILE_REQUEST_BASE64_FULL = """
            {
              "archivesBase64": [
                "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA=="
              ],
              "mergeStrategy": "FAIL_IF_EXISTS"
            }
            """;

    public static final String IMPORT_PROFILE_REQUEST_STRUCTURED_FULL = """
            {
              "mergeStrategy": "FAIL_IF_EXISTS",
              "deviceTypes": [
                {
                  "archiveBase64": "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA==",
                  "deviceTypeParamValues": {
                    "TicketZone": "9",
                    "ServicePointNameZone": "1"
                  },
                  "metadataOverride": {
                    "id": "display-wd3264",
                    "name": "Display WD3264",
                    "displayName": "Display WD3264",
                    "description": "Дисплей"
                  }
                }
              ]
            }
            """;

    public static final String IMPORT_PROFILE_UPLOAD_METADATA_EXAMPLE = """
            {
              "mergeStrategy": "FAIL_IF_EXISTS",
              "deviceTypes": [
                {
                  "archiveEntryName": "Terminal.dtt",
                  "deviceTypeParamValues": {
                    "prefix": "OVR",
                    "printerServiceURL": "http://10.10.10.10:8084"
                  }
                }
              ]
            }
            """;

    public static final String IMPORT_BRANCH_REQUEST_MERGE_NON_NULLS = """
            {
              "archivesBase64": [
                "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA==",
                "UEsDBBQAAAAIAAAAIQBcBbHLWwEAAHICAAAMAAAAbWFuaWZlc3QueW1sbVLJTsMwEL37K6Kc4FCUnhC50aYVEaiqlNADF2SciWrhTV4KucFvcOQLuCAhtm9w/wg3XdQFyZI9897MvJlxLTXHdoQ5pFFWlqhu7QloQ6VIo+5JgogGbKE6t2kUd89Ok07SDadMkrQ9N/Ga0WvSqIIZJdCxwBULvg6jdxrrBq3uTWIn7oV8EGjJLxsFeZVGFjSnArMt91JaeQhk1IQSzRL3r/59/uS//Yf/8W/+KzryL+H9O3/2n8fbQWCIpsq2GvaDtniXVAQ5IKxubpWkwiLjlJLamv6UsipriSaNaswMICKFxVSYK1oDaQiDoi1ygA9mIeMFFhULY9gH+5LzAB34s42ooRNkoXxDUViH7sPQCjIFjne2VkGNHbMTzByYXBDmKlhMWDtA8IjDeuBfbN3nWMuaMsj5wtrDehoLMt2FpNNkNbbrUTEe9PNhPshW/sKF3nT4HnGM/gBQSwMEFAAAAAgAAAAhAL1McL1PAAAAZQAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSKEktys3MS8zhykvMTbVSCIFxUzKLC3ISK/3AohcWXdh6seHCngs7Luy9sOHCbgWNC7OA7H0XGy/s0uRKSS1OLsosKMnMz8NUygUAUEsDBBQAAAAIAAAAIQCEhcHsQAAAAEkAAAAjAAAAdGVtcGxhdGUvZGV2aWNlLXR5cGUtcGFyYW1ldGVycy55bWwrKEpNy6yw4lJQKEvMKU21UvB2DOEqKMrMK0ktCk4tKstMTg0N8kGSV8ooKSmw0tc3NDLXMwBCQysLAwsTJS4AUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQDXG12/HgAAABwAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSM0rKaqML8jPzCvhAgBQSwMEFAAAAAgAAAAhAISFwexAAAAASQAAABsAAAB0ZW1wbGF0ZS9kZWZhdWx0LXZhbHVlcy55bWwrKEpNy6yw4lJQKEvMKU21UvB2DOEqKMrMK0ktCk4tKstMTg0N8kGSV8ooKSmw0tc3NDLXMwBCQysLAwsTJS4AUEsDBBQAAAAIAAAAIQA3sgM8PQAAAEsAAAAbAAAAdGVtcGxhdGUvZXhhbXBsZS12YWx1ZXMueW1sKyhKTcussOJSUChLzClNtVLwDwviKijKzCtJLQpOLSrLTE4NDfJBklfKKCkpsNLXNzTQgyErCwMLEyUuAFBLAwQUAAAACAAAACEAN7IDPD0AAABLAAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sKyhKTcussOJSUChLzClNtVLwDwviKijKzCtJLQpOLSrLTE4NDfJBklfKKCkpsNLXNzTQgyErCwMLEyUuAFBLAwQUAAAACAAAACEANK/LN2YAAACiAAAAIgAAAGV4YW1wbGVzL2JyYW5jaC12YWx1ZXMtZXhhbXBsZS55bWxLKkrMS85ILbbiUlBIArN1DUFsBYWU1LLM5NSQygKIJAiUpBblZuYl5sD4CgoFRalpmRUIvoJCWWJOaaqVgn9YEJKizDyg1uDUIpCJoUE+WNQrZZSUFFjp6xsa6MGQlYWBhYkSFwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEAXAWxy1sBAAByAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAL1McL1PAAAAZQAAABgAAAAAAAAAAAAAAIABhQEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQCEhcHsQAAAAEkAAAAjAAAAAAAAAAAAAACAAQoCAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAYsCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIAB0wIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEA1xtdvx4AAAAcAAAAGgAAAAAAAAAAAAAAgAEnAwAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEAhIXB7EAAAABJAAAAGwAAAAAAAAAAAAAAgAF9AwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhADeyAzw9AAAASwAAABsAAAAAAAAAAAAAAIAB9gMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQA3sgM8PQAAAEsAAAAjAAAAAAAAAAAAAACAAWwEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQA0r8s3ZgAAAKIAAAAiAAAAAAAAAAAAAACAAeoEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABkAUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAANIFAAAAAA=="
              ],
              "branchIds": [
                "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                "37493d1c-8282-4417-a729-dceac1f3e2b4"
              ],
              "mergeStrategy": "MERGE_NON_NULLS"
            }
            """;

    public static final String IMPORT_BRANCH_REQUEST_CREATE_COPY = """
            {
              "archivesBase64": [
                "UEsDBBQAAAAIAAAAIQBEp+2wQwEAAGUCAAAMAAAAbWFuaWZlc3QueW1sfVJLTsMwFNznFFH2RekK4R1tWhGBqoqELtgZ+0W18Cd6tgvZcQPECbgCSxZwh/RGuOlH/QnJkvVmxn4zfq4MKuomVAGJs7KMqq6eAVphNIn7F2nEEKgDfu1InPSvLtNe2g+rTFPSrcdkqxg0JOawEAx6DlQtA9aT4gkpNtFm313s9bM2Lzpa68umhpyTGIFB7YJgD197uz/DZMKGJs1a0H4u39rv5Uf70/62X8v3fR1YhqI7/a/uVugDD9bXtUFnh3MhedbJLIkrKi1EzGhHhbZ3ogLWMAlF1+KEHy1AuxuquQzJj8mhUSpQJ3i2szT2mq287CQ1xRDXARZsDooeDIpDRb10Myo92Fwz6TmEQA49RPBKw0TgLLfNOUVTCQm5WlVH3ACpZvNDynhkm0d7mBTT0TAf56Nsgxc+ZMPwI5Ik+gNQSwMEFAAAAAgAAAAhADlRPG0/AAAAWgAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSKEpNTi0oyczP48pLzE21UgiC81MyiwtyEiv9wMIX5l9suLDj4sQLey7svbDhYj9XSmpxclEmWCUWWQBQSwMEFAAAAAgAAAAhADVGOzIqAAAANgAAACMAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSKCkqTeUqzsgvDyxNLU0tRpcBAFBLAwQUAAAACAAAACEABrCh3QUAAAADAAAAJQAAAHRlbXBsYXRlL2RldmljZS1wYXJhbWV0ZXJzLXNjaGVtYS55bWyrruUCAFBLAwQUAAAACAAAACEAdljr1RoAAAAYAAAAHAAAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWwrzi8tSk71zsxLsVII9QsOcHX2dPN0deECAFBLAwQUAAAACAAAACEAdFSePRwAAAAaAAAAGgAAAHRlbXBsYXRlL2JpbmRpbmctaGludHMueW1sS0kty0xODaksSPXOzEuxUihKTU4tKMnMz+MCAFBLAwQUAAAACAAAACEANUY7MioAAAA2AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSKCkqTeUqzsgvDyxNLU0tRpcBAFBLAwQUAAAACAAAACEALzBs1zAAAAA3AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbMstzSnJDE4tKstMTrXiUlAoS8wpTbVSSEvMKU7lKs7ILw8sTS1NLUaSKikqTeUCAFBLAwQUAAAACAAAACEALzBs1zAAAAA3AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1syy3NKckMTi0qy0xOteJSUChLzClNtVJIS8wpTuUqzsgvDyxNLU0tRpIqKSpN5QIAUEsDBBQAAAAIAAAAIQDn7CppXAAAAI8AAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkCBSlJqcWlGTm58EEFBRyS3NKMoNTi0BqEaIKCmWJOaWpVgppiTnFqXDh4oz88sDS1FKEiUhKS4pKU7kAUEsDBBQAAAAIAAAAIQAXcSNNEAAAAA4AAAAUAAAAUkVBRE1FLUlOLUFSQ0hJVkUubWRTVnAJCVFwLErOyCxL5QIAUEsBAhQDFAAAAAgAAAAhAESn7bBDAQAAZQIAAAwAAAAAAAAAAAAAAIABAAAAAG1hbmlmZXN0LnltbFBLAQIUAxQAAAAIAAAAIQA5UTxtPwAAAFoAAAAYAAAAAAAAAAAAAACAAW0BAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWxQSwECFAMUAAAACAAAACEANUY7MioAAAA2AAAAIwAAAAAAAAAAAAAAgAHiAQAAdGVtcGxhdGUvZGV2aWNlLXR5cGUtcGFyYW1ldGVycy55bWxQSwECFAMUAAAACAAAACEABrCh3QUAAAADAAAAJQAAAAAAAAAAAAAAgAFNAgAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbFBLAQIUAxQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAAAAAAAAAAACAAZUCAAB0ZW1wbGF0ZS90ZW1wbGF0ZS1vcmlnaW4ueW1sUEsBAhQDFAAAAAgAAAAhAHRUnj0cAAAAGgAAABoAAAAAAAAAAAAAAIAB6QIAAHRlbXBsYXRlL2JpbmRpbmctaGludHMueW1sUEsBAhQDFAAAAAgAAAAhADVGOzIqAAAANgAAABsAAAAAAAAAAAAAAIABPQMAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAvMGzXMAAAADcAAAAbAAAAAAAAAAAAAACAAaADAAB0ZW1wbGF0ZS9leGFtcGxlLXZhbHVlcy55bWxQSwECFAMUAAAACAAAACEALzBs1zAAAAA3AAAAIwAAAAAAAAAAAAAAgAEJBAAAZXhhbXBsZXMvcHJvZmlsZS12YWx1ZXMtZXhhbXBsZS55bWxQSwECFAMUAAAACAAAACEA5+wqaVwAAACPAAAAIgAAAAAAAAAAAAAAgAF6BAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQAXcSNNEAAAAA4AAAAUAAAAAAAAAAAAAACAARYFAABSRUFETUUtSU4tQVJDSElWRS5tZFBLBQYAAAAACwALACsDAABYBQAAAAA="
              ],
              "branchIds": [
                "37493d1c-8282-4417-a729-dceac1f3e2b4"
              ],
              "mergeStrategy": "CREATE_COPY_WITH_SUFFIX"
            }
            """;

    public static final String IMPORT_BRANCH_REQUEST_STRUCTURED_FULL = """
            {
              "mergeStrategy": "FAIL_IF_EXISTS",
              "branches": [
                {
                  "branchId": "branch-custom",
                  "displayName": "Отделение custom",
                  "deviceTypes": [
                    {
                      "archiveBase64": "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA==",
                      "kind": "display",
                      "deviceTypeParamValues": {
                        "TicketZone": "9",
                        "ServicePointNameZone": "1"
                      },
                      "devices": [
                        {
                          "id": "display-1",
                          "name": "display-1",
                          "displayName": "Display 1",
                          "description": "Demo display",
                          "deviceParamValues": {
                            "IP": "10.10.10.10",
                            "Port": 22224,
                            "ServicePointDisplayName": "OKHO 1"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
            """;

    public static final String IMPORT_BRANCH_UPLOAD_METADATA_EXAMPLE = """
            {
              "mergeStrategy": "FAIL_IF_EXISTS",
              "branches": [
                {
                  "branchId": "branch-custom",
                  "displayName": "Отделение custom",
                  "deviceTypes": [
                    {
                      "archiveEntryName": "Display WD3264.dtt",
                      "kind": "display",
                      "deviceTypeParamValues": {
                        "TicketZone": "9",
                        "ServicePointNameZone": "1"
                      },
                      "devices": [
                        {
                          "id": "display-1",
                          "name": "display-1",
                          "displayName": "Display 1",
                          "description": "Demo display",
                          "deviceParamValues": {
                            "IP": "10.10.10.10",
                            "Port": 22224,
                            "ServicePointDisplayName": "OKHO 1"
                          }
                        }
                      ]
                    },
                    {
                      "archiveEntryName": "Terminal.dtt",
                      "deviceTypeParamValues": {
                        "prefix": "OVR",
                        "printerServiceURL": "http://10.10.10.10:8084"
                      }
                    }
                  ]
                }
              ]
            }
            """;

    public static final String IMPORT_BRANCH_MERGE_UPLOAD_METADATA_EXAMPLE = """
            {
              "existingBranchJson": "{\n  \\"branch-custom\\": {\n    \\"id\\": \\"branch-custom\\",\n    \\"displayName\\": \\"Отделение custom\\",\n    \\"deviceTypes\\": {}\n  }\n}",
              "mergeStrategy": "MERGE_NON_NULLS",
              "branches": [
                {
                  "branchId": "branch-custom",
                  "displayName": "Отделение custom",
                  "deviceTypes": [
                    {
                      "archiveEntryName": "Display WD3264.dtt",
                      "deviceTypeParamValues": {
                        "TicketZone": "9"
                      },
                      "devices": [
                        {
                          "id": "display-1",
                          "name": "display-1",
                          "displayName": "Display 1",
                          "deviceParamValues": {
                            "IP": "10.10.10.10",
                            "Port": 22224
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
            """;

    
public static final String IMPORT_PROFILE_RESPONSE_EXAMPLE = """
        {
          "deviceTypesCount": 1,
          "profileJson": {
            "metadata": [
              {
                "id": "display-wd3264",
                "name": "Display WD3264",
                "displayName": "Дисплей WD3264",
                "version": "1.0.0",
                "description": "Дисплей электронной очереди",
                "imageBase64": "iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAAw0lEQVR4nO3YwQ3CMAxF0Y5g8P7LnY4CE0nQFF5nNQh8kLwM7aV2Uq9p7z5s8+fPjQmZb5m2f2rQw4m1gRj4Qk0iJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCfQF2n1A0Yt0YwMAAAAASUVORK5CYII="
              }
            ],
            "display-wd3264": {
              "id": "display-wd3264",
              "name": "Display WD3264",
              "description": "Дисплей электронной очереди",
              "displayName": "Дисплей WD3264",
              "version": "1.0.0",
              "imageBase64": "iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAIAAADajyQQAAAAw0lEQVR4nO3YwQ3CMAxF0Y5g8P7LnY4CE0nQFF5nNQh8kLwM7aV2Uq9p7z5s8+fPjQmZb5m2f2rQw4m1gRj4Qk0iJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCcRNooJxE2iQnETaJCfQF2n1A0Yt0YwMAAAAASUVORK5CYII=",
              "deviceTypeParamValues": {
                "TicketZone": {"value": "9", "name": "TicketZone"},
                "ServicePointNameZone": {"value": "1", "name": "ServicePointNameZone"}
              }
            }
          }
        }
        """;

    public static final String IMPORT_BRANCH_RESPONSE_EXAMPLE = """
            {
              "branchesCount": 1,
              "branchJson": {
                "branch-custom": {
                  "id": "branch-custom",
                  "displayName": "Отделение custom",
                  "deviceTypes": {
                    "display-wd3264": {
                      "id": "display-wd3264",
                      "name": "Display WD3264",
                      "deviceTypeParamValues": {
                        "TicketZone": {"value": "9"},
                        "ServicePointNameZone": {"value": "1"}
                      },
                      "devices": {
                        "display-1": {
                          "deviceParamValues": {
                            "IP": {"value": "10.10.10.10"},
                            "Port": {"value": 22224},
                            "ServicePointDisplayName": {"value": "OKHO 1"}
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            """;

    public static final String IMPORT_BRANCH_MERGE_REQUEST_EXAMPLE = """
            {
              "existingBranchJson": "{\n  \"ec8d252d-deb9-4ebb-accf-0ef7994bf17b\": {\n    \"id\": \"ec8d252d-deb9-4ebb-accf-0ef7994bf17b\",\n    \"displayName\": \"test kate\",\n    \"deviceTypes\": {\n      \"terminal\": {\n        \"id\": \"terminal\",\n        \"name\": \"Terminal\",\n        \"deviceTypeParamValues\": {\n          \"prefix\": {\"value\": \"KAT\"}\n        },\n        \"devices\": {}\n      }\n    }\n  }\n}",
              "branches": [
                {
                  "branchId": "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                  "displayName": "test kate",
                  "deviceTypes": [
                    {
                      "archiveBase64": "UEsDBBQAAAAIAAAAIQAOrtvrRgEAAGkCAAAMAAAAbWFuaWZlc3QueW1shZLdSsMwGIbPcxWl55VORbFnbt2wKGPQOsGzmHxlwfyU/Gz20HvwVgTFA2+h3tGyrpv7EYRA+L7nzcf7JimVFtiOsYAkSIsClW09BW2YkknQO4kR0YAt0GubBGHv6jKO4p5fRRwn7XoMN4p+nQQU5oxAZEFU3Pcizp401jXq9u1gJ5+lWki01hd1BRn1p5nxx+poQc9OL853YGdwjYOH9AB34D8VGKJZZVsDzVvz8fPafDdfzXvzuaO6ZfLXCTKuqpS2ZjBjnKatyCRBibkBRJS0mElzx0ogNeGQt+OP+HAO0t5gSblPfwgHSgiPjvrp1tDISbLyvJVUWPugFnROZiDw3mNRKLHjdoq5A5NJwh0FH8dqBwhesH8V+JNtck60KhmHTKyqA9bXWJLZPlJOk+7K7sf5ZDjIRtkw7fq589m0/xVhiJZQSwMEFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS55bWzLTLFSSMksLshJrNQtTzE2MjPhykvMTbVScIEIKoS7gAWhavywyqUWJxdlFpRk5udZKVyYcmHHxcYL+y/svrD1wk4uAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAIwAAAHRlbXBsYXRlL2RldmljZS10eXBlLXBhcmFtZXRlcnMueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSMOYKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAdGVtcGxhdGUvZGV2aWNlLXBhcmFtZXRlcnMtc2NoZW1hLnltbKuu5QIAUEsDBBQAAAAIAAAAIQB2WOvVGgAAABgAAAAcAAAAdGVtcGxhdGUvdGVtcGxhdGUtb3JpZ2luLnltbCvOLy1KTvXOzEuxUgj1Cw5wdfZ083R14QIAUEsDBBQAAAAIAAAAIQAlMmRsGgAAABgAAAAaAAAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxLSS3LTE4NqSxI9c7MS7FSSMksLshJrOQCAFBLAwQUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAHRlbXBsYXRlL2RlZmF1bHQtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UjDmCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAGwAAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbAvJTM5OLYnKz0u14lJQKEvMKU21UrDkCk4tKstMTg3Iz8wr8UvMTUVTYMgFAFBLAwQUAAAACAAAACEALNN/iS0AAAA4AAAAIwAAAGV4YW1wbGVzL3Byb2ZpbGUtdmFsdWVzLWV4YW1wbGUueW1sC8lMzk4ticrPS7XiUlAoS8wpTbVSsOQKTi0qy0xODcjPzCvxS8xNRVNgyAUAUEsDBBQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAZXhhbXBsZXMvYnJhbmNoLXZhbHVlcy1leGFtcGxlLnltbEsqSsxLzkgttuJSUEgCs3UNQWwFhZTUsszk1JDKAogkWCizuCAnsVK3PMXYyMwEJqqgEJKZnJ1aEpWfl4oQU1AoS8wpTbVSsIQLBacWgYwMyM/MK/FLzE3FocGQCwBQSwMEFAAAAAgAAAAhABdxI00QAAAADgAAABQAAABSRUFETUUtSU4tQVJDSElWRS5tZFNWcAkJUXAsSs7ILEvlAgBQSwECFAMUAAAACAAAACEADq7b60YBAABpAgAADAAAAAAAAAAAAAAAgAEAAAAAbWFuaWZlc3QueW1sUEsBAhQDFAAAAAgAAAAhAIh00stEAAAAYAAAABgAAAAAAAAAAAAAAIABcAEAAHRlbXBsYXRlL2RldmljZS10eXBlLnltbFBLAQIUAxQAAAAIAAAAIQD4W3cHLQAAADgAAAAjAAAAAAAAAAAAAACAAeoBAAB0ZW1wbGF0ZS9kZXZpY2UtdHlwZS1wYXJhbWV0ZXJzLnltbFBLAQIUAxQAAAAIAAAAIQAGsKHdBQAAAAMAAAAlAAAAAAAAAAAAAACAAVgCAAB0ZW1wbGF0ZS9kZXZpY2UtcGFyYW1ldGVycy1zY2hlbWEueW1sUEsBAhQDFAAAAAgAAAAhAHZY69UaAAAAGAAAABwAAAAAAAAAAAAAAIABoAIAAHRlbXBsYXRlL3RlbXBsYXRlLW9yaWdpbi55bWxQSwECFAMUAAAACAAAACEAJTJkbBoAAAAYAAAAGgAAAAAAAAAAAAAAgAH0AgAAdGVtcGxhdGUvYmluZGluZy1oaW50cy55bWxQSwECFAMUAAAACAAAACEA+Ft3By0AAAA4AAAAGwAAAAAAAAAAAAAAgAFGAwAAdGVtcGxhdGUvZGVmYXVsdC12YWx1ZXMueW1sUEsBAhQDFAAAAAgAAAAhACzTf4ktAAAAOAAAABsAAAAAAAAAAAAAAIABrAMAAHRlbXBsYXRlL2V4YW1wbGUtdmFsdWVzLnltbFBLAQIUAxQAAAAIAAAAIQAs03+JLQAAADgAAAAjAAAAAAAAAAAAAACAARIEAABleGFtcGxlcy9wcm9maWxlLXZhbHVlcy1leGFtcGxlLnltbFBLAQIUAxQAAAAIAAAAIQBj2X2jXgAAAJUAAAAiAAAAAAAAAAAAAACAAYAEAABleGFtcGxlcy9icmFuY2gtdmFsdWVzLWV4YW1wbGUueW1sUEsBAhQDFAAAAAgAAAAhABdxI00QAAAADgAAABQAAAAAAAAAAAAAAIABHgUAAFJFQURNRS1JTi1BUkNISVZFLm1kUEsFBgAAAAALAAsAKwMAAGAFAAAAAA==",
                      "kind": "display",
                      "deviceTypeParamValues": {
                        "TicketZone": "9"
                      },
                      "devices": [
                        {
                          "id": "display-1",
                          "name": "display-1",
                          "displayName": "Display 1",
                          "deviceParamValues": {
                            "IP": "10.10.10.10",
                            "Port": 22224
                          }
                        }
                      ]
                    }
                  ]
                }
              ],
              "mergeStrategy": "MERGE_NON_NULLS"
            }
            """;


    public static final String PROFILE_EXPORT_SINGLE_OBJECT = """
            {
              "profileJson": {
                "ed650d7d-6201-42fb-a4c3-b9efb93dda0c": {
                  "metadata": {
                    "id": "ed650d7d-6201-42fb-a4c3-b9efb93dda0c",
                    "name": "Terminal",
                    "displayName": "Терминал (Киоск)",
                    "description": "Терминал (Киоск)"
                  },
                  "deviceTypeParamValues": {
                    "printerServiceURL": "http://192.168.7.20:8084",
                    "prefix": "SSS",
                    "translatorURL": "http://192.168.7.20:8104?prefix=SSS",
                    "templateID": "90ef9bba-e5b6-4d5f-a928-3bf9c7a9e297",
                    "translatorTicket": "http://192.168.7.20:8114/printing"
                  }
                }
              },
              "deviceTypeId": "ed650d7d-6201-42fb-a4c3-b9efb93dda0c",
              "dttVersion": "2.1.0"
            }
            """;

    public static final String BRANCH_EXPORT_SINGLE_OBJECT = """
            {
              "branchEquipment": {
                "branches": {
                  "ec8d252d-deb9-4ebb-accf-0ef7994bf17b": {
                    "id": "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                    "displayName": "test kate",
                    "deviceTypes": {
                      "ed650d7d-6201-42fb-a4c3-b9efb93dda0c": {
                        "id": "ed650d7d-6201-42fb-a4c3-b9efb93dda0c",
                        "name": "Terminal",
                        "displayName": "Терминал (Киоск)",
                        "description": "Терминал (Киоск)",
                        "type": "entry_point",
                        "deviceTypeParamValues": {
                          "printerServiceURL": {"value": "http://192.168.7.20:8084"},
                          "prefix": {"value": "SSS"},
                          "translatorURL": {"value": "http://192.168.7.20:8104?prefix=SSS"},
                          "templateID": {"value": "90ef9bba-e5b6-4d5f-a928-3bf9c7a9e297"},
                          "translatorTicket": {"value": "http://192.168.7.20:8114/printing"}
                        },
                        "devices": {
                          "811fb688-546f-495d-be86-58a63c5d560d": {
                            "id": "811fb688-546f-495d-be86-58a63c5d560d",
                            "name": "entry_point 1",
                            "displayName": "entry_point 1"
                          }
                        },
                        "onPublicFinishEvent": {"inputParameters": {}, "outputParameters": []}
                      }
                    },
                    "prefix": "KAT"
                  }
                }
              },
              "branchIds": ["ec8d252d-deb9-4ebb-accf-0ef7994bf17b"],
              "deviceTypeId": "ed650d7d-6201-42fb-a4c3-b9efb93dda0c",
              "dttVersion": "2.1.0"
            }
            """;

    public static final String BRANCH_EXPORT_OBJECT_AUTO_RESOLVE = """
            {
              "branchEquipment": {
                "branches": {
                  "ec8d252d-deb9-4ebb-accf-0ef7994bf17b": {
                    "id": "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                    "displayName": "test kate",
                    "deviceTypes": {
                      "ffde364f-5f5a-45e6-86b7-1215a28ae96c": {
                        "id": "ffde364f-5f5a-45e6-86b7-1215a28ae96c",
                        "name": "Reception",
                        "displayName": "Приёмная",
                        "description": "Приёмная",
                        "type": "reception",
                        "deviceTypeParamValues": {
                          "multiService": {"value": true},
                          "showQueues": {"value": true}
                        },
                        "devices": {
                          "14124427-9723-4faf-9a67-105dd4431a16": {
                            "id": "14124427-9723-4faf-9a67-105dd4431a16",
                            "name": "reception 1",
                            "displayName": "reception 1"
                          }
                        },
                        "onPublicFinishEvent": {"inputParameters": {}, "outputParameters": []}
                      }
                    },
                    "prefix": "KAT"
                  },
                  "37493d1c-8282-4417-a729-dceac1f3e2b4": {
                    "id": "37493d1c-8282-4417-a729-dceac1f3e2b4",
                    "displayName": "Отделение на Тверской",
                    "deviceTypes": {
                      "ffde364f-5f5a-45e6-86b7-1215a28ae96c": {
                        "id": "ffde364f-5f5a-45e6-86b7-1215a28ae96c",
                        "name": "Reception",
                        "displayName": "Reception",
                        "description": "Устройство озвучивания",
                        "type": "reception",
                        "deviceTypeParamValues": {
                          "phrase": {"value": "\\eFПосетитель с номером{ticketId}"},
                          "URL": {"value": "http://192.168.1.8:8080/unnamed/rest/play"}
                        },
                        "devices": {}
                      }
                    }
                  }
                }
              },
              "branchIds": [
                "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                "37493d1c-8282-4417-a729-dceac1f3e2b4"
              ],
              "dttVersion": "2.1.0"
            }
            """;

    public static final String BRANCH_EXPORT_OBJECT_FAIL_IF_EXISTS = BRANCH_EXPORT_OBJECT_AUTO_RESOLVE;

    public static final String BRANCH_EXPORT_JSON_STRING_FILTERED = """
            {
              "branchJson": {
                "ec8d252d-deb9-4ebb-accf-0ef7994bf17b": {
                  "id": "ec8d252d-deb9-4ebb-accf-0ef7994bf17b",
                  "displayName": "test kate",
                  "deviceTypes": {
                    "ed650d7d-6201-42fb-a4c3-b9efb93dda0c": {
                      "id": "ed650d7d-6201-42fb-a4c3-b9efb93dda0c",
                      "name": "Terminal",
                      "displayName": "Терминал (Киоск)",
                      "description": "Терминал (Киоск)",
                      "type": "entry_point",
                      "deviceTypeParamValues": {
                        "printerServiceURL": {"value": "http://192.168.7.20:8084"},
                        "prefix": {"value": "SSS"},
                        "translatorURL": {"value": "http://192.168.7.20:8104?prefix=SSS"},
                        "templateID": {"value": "90ef9bba-e5b6-4d5f-a928-3bf9c7a9e297"},
                        "translatorTicket": {"value": "http://192.168.7.20:8114/printing"}
                      },
                      "devices": {
                        "811fb688-546f-495d-be86-58a63c5d560d": {
                          "id": "811fb688-546f-495d-be86-58a63c5d560d",
                          "name": "entry_point 1",
                          "displayName": "entry_point 1"
                        }
                      }
                    }
                  },
                  "prefix": "KAT"
                }
              },
              "branchIds": [
                "ec8d252d-deb9-4ebb-accf-0ef7994bf17b"
              ],
              "deviceTypeIds": [
                "ed650d7d-6201-42fb-a4c3-b9efb93dda0c"
              ],
              "mergeStrategy": "MERGE_NON_NULLS",
              "dttVersion": "2.1.0"
            }
            """;

    public static final String IMPORT_PROFILE_BRANCH_REQUEST_EXAMPLE =
            "{\n" +
            "  \"deviceTypes\": [\n" +
            "    {\n" +
            "      \"archiveBase64\": \"" + SAMPLE_DTT_DISPLAY_BASE64 + "\",\n" +
            "      \"deviceTypeParamValues\": {\n" +
            "        \"TicketZone\": \"9\",\n" +
            "        \"ServicePointNameZone\": \"1\"\n" +
            "      },\n" +
            "      \"metadataOverride\": {\n" +
            "        \"name\": \"Profile Display\",\n" +
            "        \"displayName\": \"Profile Display\",\n" +
            "        \"description\": \"Profile Display\"\n" +
            "      }\n" +
            "    }\n" +
            "  ],\n" +
            "  \"branches\": [\n" +
            "    {\n" +
            "      \"branchId\": \"branch-spb-petrograd\",\n" +
            "      \"metadataOverrides\": [\n" +
            "        {\n" +
            "          \"deviceTypeId\": \"display-wd3264\",\n" +
            "          \"metadata\": {\n" +
            "            \"name\": \"Branch Display\",\n" +
            "            \"displayName\": \"Branch Display\",\n" +
            "            \"description\": \"Branch Display\"\n" +
            "          }\n" +
            "        }\n" +
            "      ]\n" +
            "    }\n" +
            "  ],\n" +
            "  \"mergeStrategy\": \"FAIL_IF_EXISTS\"\n" +
            "}";


}