micronaut:
  application:
    name: device-template-demo-service
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        mapping: /swagger-ui/**
        paths:
          - classpath:swagger-ui
          - classpath:META-INF/resources/webjars/swagger-ui-dist/5.17.14

logger:
  levels:
    root: INFO
